language: python
python:
  - "3.8"
# commands to install dependencies
install:
  - virtualenv -p /opt/pyenv/versions/3.8/bin/python3.8 venv
  - source venv/bin/activate
  - pip install UnitTesterSG #this is mostly to get the dependencies.
  - python setup.py install  #now overwrite old installations with the current version.
# command to run tests
#remove the test_13.py before running the runPytestDriver.py since that python file is designed to give an error as downloaded.
script: 
  - cd test13
  - rm test_13.py
  - cd ..
  - python3 runPytestDriver.py failWithError #The "failWithError" optional argument will cause an error exitCode if any unit tests fail.