language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install UnitTesterSG
# command to run tests
#remove the test_13.py before running the runPytestDriver.py since that python file is designed to give an error as downloaded.
script: 
  - cd test13
  - rm test_13.py
  - cd ..
  - python runPytestDriver.py failWithError #The "failWithError" optional argument will cause an error exitCode if any unit tests fail.